apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream auth_service {
            server auth-service:5001;
        }

        upstream task_service {
            server task-service:5002;
        }

        server {
            listen 80;

            location /auth/ {
                rewrite ^/auth/(.*)$ /$1 break;
                proxy_pass http://auth_service;
            }

            location /tasks/ {
                rewrite ^/tasks/(.*)$ /$1 break;
                proxy_pass http://task_service;
            }
        }
    }